# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDUHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for SDUHelper
  pod "SwiftSoup"
  pod "Alamofire"
  pod "Firebase/Analytics"
  pod "Firebase/Auth"
  pod "Firebase/Database"
  pod "SVProgressHUD"
end
